# Formas de financiar o projeto Nossa Maternidade

github: # Substitua com seu nome de usuário do GitHub
patreon: # Substitua com seu nome de usuário do Patreon
open_collective: # Substitua com o nome da sua organização Open Collective
ko_fi: # Substitua com seu nome de usuário do Ko-fi
custom: ['https://www.nossa-maternidade.com/doar']

